FISH-8465 Add support for remote local instance collection
payara/Diagnostics-Tool pull request #21
Opened 2024-03-27 16:17 UTC by kalinchan

Created a new command to get the instance install root
Used this to pass to domain and log collector
You can add the `-p` parameter to the collect-diagnostics command to make heap dump, thread dump and jvm report work i.e. `./asadmin -p 24848 collect-diagnostics --target example`

I also moved all of the domain operations to a new DomainUtil class.

# Testing
Verified the following:

- Collecting Things™ from a local DAS
  - It should be possible to collect Things™ from a DAS that is local to where you run the asadmin command from:
    - If the DAS is online, All the Things™
    - If the DAS is offline, just the log and domain.xml
  - This includes accounting for scenarios where there may be more than one domain.
  - This includes accounting for scenarios where you're using a custom domain dir.
 
- Collecting Things™ from an instance on the same machine as the DAS
  - It should be possible to collect Things™ from an instance in a domain that is local to where you run the asadmin command from:
    - If the instance is online, All the Things™
    - If the instance is offline, just the log and domain.xml
  - This includes accounting for scenarios where there may be more than one domain.
  - This includes accounting for scenarios where you're using a custom node directory.
  - It should not matter if the DAS is running or not.

- Collecting Things™ from an instance that exists on a different machine to the DAS
  - It should be possible to collect Things™ from an instance in a domain that is local to where you run the asadmin command from:
    - If the instance is online, All the Things™
    - If the instance is offline, just the log and domain.xml
  - This includes accounting for scenarios where you're using a custom node directory.
  - It should not matter if the remote DAS is running or not.

# Notes
Previous PR should be merged first

2024-03-28 11:51 UTC, Pandrex247 requested changes

2024-03-28 11:51 UTC, Pandrex247 commented on src/main/java/fish/payara/extras/diagnostics/asadmin/CollectAsadmin.java
> +                    params.put(ParamConstants.LOGS_PATH, getDomainRootDir().getPath() + "/logs");
```suggestion
                    params.put(ParamConstants.LOGS_PATH, getDomainRootDir().getPath() + File.separator() + "logs");
```

2024-03-28 11:51 UTC, Pandrex247 commented on src/main/java/fish/payara/extras/diagnostics/asadmin/LocalInstanceCommand.java
Why have you copied this file? You shouldn't need to

2024-03-28 11:55 UTC, kalinchan commented on src/main/java/fish/payara/extras/diagnostics/asadmin/LocalInstanceCommand.java
I couldn't import it ):

2024-03-28 16:14 UTC, Pandrex247 commented on src/main/java/fish/payara/extras/diagnostics/asadmin/LocalInstanceCommand.java
Then add the dependency 😝
```
        <dependency>
            <groupId>fish.payara.server.internal.cluster</groupId>
            <artifactId>cluster-cli</artifactId>
            <version>${payara.version}</version>
        </dependency>
```

2024-03-29 12:18 UTC, Pandrex247 approved these changes

2024-03-29 12:36 UTC, merged